### ISSUE TITLE
How to get backend running?

### ISSUE THREAD

**Issue by ghost** [siong1987/siongTime-web#3]
Hai, stumbled upon your project on GitHub any info on getting the backend up and running? I'm assuming it's going to need to be hooked up to an external movie/tvshow api?

**Comment by sssionggg** [comment]
@JakeRound Yes, you need to hook it up to an external movie/tvshow API.

**Comment by sssionggg** [comment]
Also, you need a server to keep the backend running too.

**Comment by ghost** [comment]
Ahh thanks! Little bit complex for my understanding. It would be cool to run backend on a Raspberry Pi though instead of a decent server? Reminds me much of @osterdev old Project PopcornTV.
